language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: francis.provost@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
